### ISSUE TITLE
would like something similar for projects

### ISSUE THREAD

**Issue by danielskatz** [nayafia/lemonade-stand#1]
I tend to think about things from the point-of-view of projects as well.  And often, I think that projects need to acquire resources to do work.  Sustainable projects are those where the resources needed to do the work to keep the project going continue to be acquired over time.  Given this, and the fact that your current page is about how an individual can get resources, it would be useful to have a similar document for a project.  This might include many of the same things, but it also might include other resources, such as volunteer labor, company-paid labor, donated services (hardware, software, cycle, bytes, etc.), and other things.

If you are interested in this, I would be happy to contribute.  If not, _eventually_ I will start something like this myself :)

**Comment by nayafia** [comment]
Hi! I wrote this with both the individual/project in mind, but focusing specifically on finding $$ rather than other types of resources.

I think a document around finding contributors, in-kind donations, etc would be *very* useful but out of the scope of this project. That overlaps with a bunch of other projects ideas I've had rattling around in my head, though, so hopefully it'll get sucked into one of them :) if you do start something like it, I'd love to see it!

**Comment by danielskatz** [comment]
You might want to change some of this to make this clear at the start, such as changing "I do open source work, how do I get paid for it?"
