### ISSUE TITLE
New example / section: company open source sponsoring (Spice Program)

### ISSUE THREAD

**Issue by kimmobrunfeldt** [nayafia/lemonade-stand#13]
Thanks for the very nice summary of the various models to finance a project! :) I just wanted to add to the [Start a project while currently employed](https://github.com/nayafia/lemonade-stand#start-a-project-while-currently-employed) section that some companies are also sponsoring for **any** open source project you might be working on your free time. 

You can read more about how the Spice Program works in our company: http://futurice.com/blog/sponsoring-free-time-open-source-activities. Hopefully this didn't come out as too pushy marketing, but as a new possible example for the list.

I would've created a new pull request but I'm not sure if this would be a new section on its own or an addition to the existing section(Start a project while currently employed). For example the existing cons are not exactly true for Spice Program: 

>  Risk of undue company influence

The program allows any contribution, without any ties to the company.

>  Can lead to complicated governance later down the line

All IPR is owned by the employees, not the company.

**Comment by nayafia** [comment]
Hi, thanks for the comment! I wanted to focus on categories that a person looking for funding can have control over (ex. in the case of the Spice Program, since it's for FT employees, the person would have to work at your company, which isn't very helpful to most people).

I like that your link transparently documents how the program works at your company, though. I think that could help people advocate for themselves at their current place of employment. I just added it as a case study. Thanks!
