### ISSUE TITLE
Expand 'get hired' section

### ISSUE THREAD

**Issue by ionelmc** [nayafia/lemonade-stand#22]
For me the only interesting section is: https://github.com/nayafia/lemonade-stand#get-hired-by-a-company-to-work-on-project

Everything else only applies to people who already have very popular projects or are willing to risk/invest time or job security to achieve said popularity. Unfortunately I am neither of those.

What would be extremely valuable for me is a a list of companies that hire for OSS work or allow such work (and to what degree). Is there anything like that?

**Comment by spekulatius** [comment]
Same for me - building up a community is hard work. Working for OS company makes it way easier. There are some places around - yet it costs quite some work to find them...

**Comment by nayafia** [comment]
That's a great idea (and great perspective!).

From what I've seen so far, work arrangements happen sort of by chance, based on reputation or prior relationship (ex. Ryan Dahl's account of how he found Joyent, linked in that section). I would guess that companies that rely heavily on a certain technology (ex. Cognitect's relationship to Clojure), esp ones that do more client work than building consumer facing products, would be more friendly to open source work.

AFAIK there isn't a list of companies but that's a really great idea for a project 😃

**Comment by waldyrious** [comment]
> @ionelmc:
> What would be extremely valuable for me is a a list of companies that hire for OSS work or allow such work (and to what degree). Is there anything like that?

> @spekulatius:
> Working for OS company makes it way easier. There are some places around - yet it costs quite some work to find them...

> @nayafia:
> AFAIK there isn't a list of companies but that's a really great idea for a project :smiley:

FWIW, there have been some work collecting such companies in the [fossjobs wiki](https://github.com/fossjobs/fossjobs/wiki/resources) (/cc @moba and @pabs3 who participated in discussion to create that page in https://github.com/fossjobs/fossjobs/issues/19).

It might also be worth taking a look at https://github.com/opencompany/awesome-open-company#companies, although the latter isn't exclusively about FOSS.

That said, I'm also not sure to which extent there is an overlap with the sections [SaaS](https://github.com/nayafia/lemonade-stand#saas), [Dual license](https://github.com/nayafia/lemonade-stand#dual-license), [Open core](https://github.com/nayafia/lemonade-stand#open-core), [Foundations & consortiums](https://github.com/nayafia/lemonade-stand#foundations--consortiums) and [Venture capital](https://github.com/nayafia/lemonade-stand#venture-capital) of this repo. @nayafia, I'd appreciate if you could clarify this.

**Comment by nayafia** [comment]
@waldyrious yeah I think that overlaps with the other sections (the original discussion in this thread is about companies that have hired OSS developers), but if there are companies on those lists that you think would be great case studies for one of these sections (ex. a great example of an open core company), feel free to open a PR.

**Comment by waldyrious** [comment]
> the original discussion in this thread is about companies that have hired OSS developers

Just to make sure we're on the same page: from the excerpts I quoted in my previous comment, it sounds to me that @ionelmc and @spekulatius were talking about companies that hire developers to perform OSS work (i.e. companies whose software products are entirely or partially open source, or otherwise provide associated services), rather than companies that hire OSS developers, not necessarily to do OSS work. Is the latter what you meant, or did I misread you?

I guess my confusion comes from the description of those sections; e.g. for [SaaS](https://github.com/nayafia/lemonade-stand#saas): 
> SaaS means Software as a Service. In this model, the codebase itself can remain open source, but you offer paid services ...

Who does the "you" primarily refer to in the sentence above? Individual developers? Companies that might hire individual developers? Companies built by OSS developers who decided to pursue this model?

I think it's important to make it clear whether the intended audience of those sections is project/communities that could study and replicate the same funding models, e.g. become a SaaS company, form a foundation, etc. -- or whether they are meant for individual contributors to projects supported by such organizations, and are seeking ways to fund their OSS work (which IIUC is what this thread was initially about).
