### ISSUE TITLE
Split Open Core & Paid

### ISSUE THREAD

**Issue by dcramer** [nayafia/lemonade-stand#5]
Very differently models IMO. Often open core ends up focusing on crippling the product so that entities will pay money for the *good* features. Typically Open Core companies also offer support, services, and training, though I'd say thats not exclusive, and often exists throughout all open source companies.

Sentry for example has a paid offering, but its entirely open source (our enterprise offering is the same code).

I'd look at things like Cassandra, Riak, Cloudera, Mesosphere, Docker, and Elastic to classify in these, but I think most of them will fall in the open core world.

(I realize that a lot of the above are "real" companies, but I think thats an important differentiator in projects that make money)

**Comment by dcramer** [comment]
Also overlaps with #2

**Comment by aterrel** [comment]
Added #6 which I think is close to what you are thinking here. I feel its different from Open Core / Paid, which I would call Delayware, ie, updates to free are delayed to community. Like Cassandra.

**Comment by nayafia** [comment]
Thanks for this. I had originally thought about that whole category as "figure out some aspect of your product to charge for" (as opposed to, say, donations).

I want to avoid going too into the weeds with different business models, but happy to split this one out. 

Sidekiq, Sentry should be paid, yes?
Travis CI I'll move to managed/hosted.
Docker, Elastic, Mesosphere are examples of open core?

Also feel free to submit a PR, otherwise I'll do my best at assessing relative pros/cons :)

**Comment by nayafia** [comment]
After looking at #2, maybe I can just rename "Managed & Hosted" to SaaS, put Sidekiq/Sentry/Travis in there, and then use the above examples for open core? Two categories total. Would that make sense?

**Comment by nayafia** [comment]
Did this: https://github.com/nayafia/lemonade-stand/commit/fabb515205cfceae96a2326875278fe8d78bacbe thanks all!
