### ISSUE TITLE
Fix misleading Django success in Crowdfunding case studies

### ISSUE THREAD

**Issue by jezdez** [nayafia/lemonade-stand#8]
As noted on the [here](https://www.kickstarter.com/projects/andrewgodwin/schema-migrations-for-django/description#h:why-kickstarter) Andrew's campaign wasn't an official crowdfunding effort by the Django project, which is an important distinction to for example's Django's own only partially successful efforts to raise funds for the [Django Software Foundation](https://www.djangoproject.com/fundraising/) -- and indirectly to pay for the [Django Fellowship Program](https://www.djangoproject.com/fundraising/#fellowship-program) (et al).

As a fellow Django core developer who was *not* successful at making a living while working on Django full or even half time (despite having served as core dev, DSF director, OPs team member, translation manager, conference chair and speaker etc) I'd like to humbly point out that Andrew's success should not be advertised as the default for working on Django or in its community. There are many cautionary tales obviously and I know I'm biased, but I do feel a responsibility to prevent creating wrong expectations about the financial viability of direct work on Django.

I understand the intent of this repo, and I appreciate your efforts tremendously, the Open/Public Source community has a problem of funding, just wanted to set the record straight from my point of view. Please feel free to reach out to other Django devs to verify my claims if needed :)

**Comment by nayafia** [comment]
hi! that's understandable. I didn't mean to imply that Andrew's work was an official Django effort (and figured that was apparent since Andrew says so in his campaign description).

This question of the individual vs. the project came up in #1 as well. I think it's a tough balance because individual work on a project is de facto project work, yet I understand there is a distinction when a project has other governance in place.

I'm going to go back through the case studies and mark when it's an individual's work. For example, instead of "Django", calling it "Andrew Godwin's work on Django" or something of the like. Hopefully that will help clarify.

**Comment by nayafia** [comment]
see commit above. hope that helps!

**Comment by jezdez** [comment]
@nayafia Excellent, thank you for the changes, they make it obvious and it still hopefully encourages others enough to work on Django. Thanks!
